# Generated by Django 3.1.2 on 2020-11-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Sizeofcontainer', models.CharField(max_length=155)),
                ('From', models.CharField(max_length=155)),
                ('To', models.CharField(max_length=155)),
                ('Customer', models.CharField(max_length=155)),
                ('Carriedby', models.CharField(max_length=155)),
                ('Diesel', models.CharField(max_length=155)),
                ('Price', models.CharField(max_length=155)),
                ('Status', models.CharField(max_length=155)),
            ],
        ),
    ]
